name: hotal_trade
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  country_pickers: ^2.0.0
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: IBM Plex Sans Arabic
      fonts: 
        - asset: assets/fonts/IBMPlexSansArabicBold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansArabicRegular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabicMedium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabicSemiBold.ttf
          weight: 600
